dist: trusty
sudo: required
language: node_js
node_js:
  - "6.9"
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_install: cd public
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng test
